/**
 * User, Component, Event, User Settings table their sequence and a default user insertion
 */

/*
 * PatchTest.java
 *
 * Created on Apr 3, 2009, 3:47:59 PM
 */
package org.lss.erp.gui;

import javax.swing.JFrame;

import org.apache.log4j.Level;
import org.apache.log4j.Logger;
import org.lss.erp.common.beans.SpringBeanFactory;
import org.lss.erp.gui.component.ProgressMonitor;
import org.lss.erp.gui.component.ProgressUtil;

/**
 *
 * @author Zubair
 */
public class PatchNewComponentsAddition extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	 
    /** Creates new form PatchTest */
    public PatchNewComponentsAddition() {
        initComponents();
        setLocation(200, 200);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        progressText = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Patch");
        setMinimumSize(new java.awt.Dimension(600, 400));
        setResizable(false);

        jPanel1.setLayout(new java.awt.BorderLayout());

        progressText.setColumns(40);
        progressText.setEditable(false);
        progressText.setLineWrap(true);
        progressText.setRows(5);
        progressText.setPreferredSize(null);
        jScrollPane1.setViewportView(progressText);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("This Patch must be run before applicaiton should be launched, for once if successful.");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton1.setMnemonic('p');
        jButton1.setText("Patch");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton2.setMnemonic('x');
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        runPatch();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatchNewComponentsAddition().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea progressText;
    // End of variables declaration//GEN-END:variables

    // End of variables declaration
    // End of variables declaration
    public void runPatch() {
        final JFrame parent = this;
        Thread t = new Thread() {

            @Override
            public void run() {
               // ProgressMonitor monitor = ProgressUtil.createModalProgressMonitor(parent, 1, true, 1000);
                try {
                //	progressText.setText("Patching database...");
                  //  monitor.start("Patching database...");
                    SpringBeanFactory.getInstance();
                //    progressText.setText("Patch finished.");
                  //  monitor.setCurrent(null, 1);
                } catch (Exception e) { 
                    progressText.setText(e.getMessage());
                  //  monitor.setCurrent(null, 1);
                }
            }
        };
        t.start();
    }
}
